### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by wvanbergen** [Shopify/quantified#1]
- [x] Make sure `master` is default branch
- [x] Make repo public, and set tagline to "Pretty quantifiable measurements which feel like ActiveSupport::Duration"
- [x] Enable Travis CI
- [x] Do initial gem release

The one thing I would like to fix is the activesupport dependency. It is only used for `pluralize`. I assume we cab just replace this with a lookup table of plurals we need for the measurement systems we want to support.

@jamesmacaulay @kmcphillips

**Comment by fw42** [comment]
done

**Comment by wvanbergen** [comment]
Version 1.0.0 released
